os: linux
dist: bionic

matrix:
  include:
    - language: java
      before_install:
        - wget -O ibm-installer.bin http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/${IBM_SDK_VERSION}/linux/x86_64/ibm-java-sdk-$(sed -e 's/\./-/2' <<<${IBM_SDK_VERSION})-x86_64-archive.bin
        - chmod +x ibm-installer.bin
        - mkdir /tmp/ibm-jdk
        - PS1=">" ./ibm-installer.bin -i silent -DLICENSE_ACCEPTED=TRUE -DUSER_INSTALL_DIR=/tmp/ibm-jdk/
      install:
        - cd java
        - ./gradlew -Dibm.path=/tmp/ibm-jdk assemble
      script: ./gradlew -Dibm.path=/tmp/ibm-jdk distTar
        
    - language: cpp
      addons:
        apt:
          packages:
            - liblog4cpp5-dev
            - libnet1-dev
            - libibverbs-dev
            - libibumad-dev
            - libibmad-dev
            - libibnetdisc-dev
            - libopensm-dev
      before_install:
        - eval "MAIN_DIR=$(pwd)"
        - git clone https://github.com/nlohmann/json.git /tmp/cmake/nlohmann_json
        - cd /tmp/cmake/nlohmann_json
        - cmake .
        - cd ${MAIN_DIR}
      install:
        - cd cpp
        - mkdir -p build/
        - cd build/
        - CMAKE_PREFIX_PATH=/tmp/cmake cmake ..
      script: make

before_deploy: "tar --xform s:'build':: --xform s:'application/install/observatory':: -czvf observatory-${TRAVIS_TAG}.tar.gz cpp/build/bin/observatory java/build/application/install/observatory/ python/plot.py"
      
deploy:
  provider: releases
  token: ${ACCESS_TOKEN}
  file: observatory-${TRAVIS_TAG}.tar.gz
  on:
    repo: hhu-bsinfo/observatory
    branch: master
    tags: true
